sudo: false
language: go
go: [ 1.11.x ]

env:
  - GO111MODULE=on

install:
  # Stop go get from executing
  - true

script:
  # Build server for various operating systems
  - pushd server
  - GOOS=windows make && mv dist/prolink-server{,-windows.exe}
  - GOOS=darwin  make && mv dist/prolink-server{,-macos}
  - GOOS=linux   make && mv dist/prolink-server{,-linux}
  - popd
  # Build overlay app
  - make --directory=overlay
  # Build website
  - make --directory=website

before_deploy:
  # Replace dev-build tag with latest release
  - export OWNER=${TRAVIS_REPO_SLUG%/*}
  - git remote add gh https://${OWNER}:${GITHUB_API_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git
  - git tag -f dev-build
  - git push -f gh dev-build
  - git remote remove gh

deploy:
  - provider: releases
    api-key: $GITHUB_API_TOKEN
    name: Development Build
    body: Automatic development build of the master branch.
    file:
      - server/dist/prolink-server-windows.exe
      - server/dist/prolink-server-macos
      - server/dist/prolink-server-linux
      - overlay/dist/prolink-overlay.html
    prerelease: true
    overwrite: true
    skip_cleanup: true
    target_commitish: $TRAVIS_COMMIT
    on:
      tags: false

  - provider: pages
    github-token: $GITHUB_API_TOKEN
    skip-cleanup: true
    local-dir: website/dist
    on:
      branch: master

branches:
  only: [ master ]
