[[constraint]]
  name = "github.com/GeertJohan/go.rice"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.4.0"

[[constraint]]
  name = "github.com/gorilla/websocket"
  version = "1.1.0"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.0"

[[constraint]]
  name = "go.evanpurkhiser.com/prolink"
