version: '2'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    environment:
      - "DEFAULT_EMAIL=evanpurkhiser@gmail.com"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam
      - certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    network_mode: bridge

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-proxy-le
    volumes_from:
      - nginx-proxy
    volumes:
      - certs:/etc/nginx/certs:rw
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    network_mode: bridge

  prolink-tools:
    image: evanpurkhiser/prolink-tools-api
    container_name: prolink-tools
    environment:
      - "VIRTUAL_HOST=api.prolink.tools"
      - "LETSENCRYPT_HOST=api.prolink.tools"
    volumes:
      # This is currently a manually managed secret file on the server
      - /root/dotenv:/app/.env
    network_mode: bridge
    restart: always

volumes:
  conf:
  vhost:
  html:
  dhparam:
  certs:
  acme:
