name: build
on: [push]

jobs:
  build:
    name: build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
        - os: ubuntu-latest
          ext: tar.gz
        - os: windows-latest
          ext: exe
        - os: macos-latest
          ext: dmg
    steps:
      - uses: actions/checkout@v1
      - uses: volta-cli/action@v1

      # Build
      - run: yarn install
      - run: yarn build-main
      - run: yarn build-renderer
      - run: yarn dist

      # Uplaod built artifacts
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.os }}
          path: ${{ github.workspace }}/release/*.${{ matrix.ext }}
