name: build
on: [push]

jobs:
  build:
    name: build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v1
      - uses: volta-cli/action@v1

      # Build
      - run: yarn install
      - run: yarn build-main
      - run: yarn build-renderer
      - run: yarn dist
      - run: ls release/
      - name: Cleanup artifacts
        run: |
          npx rimraf "release/!(*.exe|*.deb|*.AppImage|*.dmg)"
      - name: Upload artifacts
      - uses: actions/upload-artifact@v2
        with:
          name: prolink-tools-${{ matrix.os }}
          path: release
