name: build
on: [push]

jobs:
  build:
    name: build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v1
      - uses: volta-cli/action@v1

      # Build
      - run: yarn install
      - run: yarn build-main
      - run: yarn build-renderer
      - run: yarn dist
      - name: Cleanup artifacts
        run: |
          npx rimraf 'release/!(*.exe|*.tar.gz|*.dmg)'
      - name: Locate built package
        id: locate
        run: |
          pkg_path="$(ls ${{ github.workspace }}/release/*)"
          echo ::set-output name=path::$pkg_path
          echo ::set-output name=name::$(basename $pkg_path)
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.locate.outputs.name }}
          path: ${{ steps.locate.outputs.path }}
