name: build
on: [push]

jobs:
  init_release:
    name: init-release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: volta-cli/action@v1
      - name: Create Sentry release
        env:
          SENTRY_ORG: evan-purkhiser
          SENTRY_PROJECT: prolink-tools
          SENTRY_AUTH_TOKEN: "${{ secrets.SENTRY_AUTH_TOKEN }}"
        run: |
          RELEASE="$(git describe)"
          curl -sL https://sentry.io/get-cli/ | bash
          sentry-cli releases new "$RELEASE"
          sentry-cli releases set-commits "$RELEASE" --auto

  build:
    name: build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
        - os: ubuntu-latest
          ext: tar.gz
        - os: windows-latest
          ext: exe
        - os: macos-latest
          ext: dmg
    steps:
      - uses: actions/checkout@v1
      - uses: volta-cli/action@v1

      # Test
      - run: yarn install
      - run: yarn lint

      # Use the short has for the  
      - name: Get filename
        id: filename
        shell: bash
        run: |
          jq; sponge;

#           [[ "${{ github.ref }}" == "refs/heads/master" ]] && \
#           npx json json -I -f package.json -e "this.name='adar'"



#           '::set-output name=name::${name}-dev-'$(git rev-parse --short HEAD)'-${os}.${ext}' || \
#           echo '::set-output name=name::${name}-${version}-${os}.${ext}'

      # Build
      - run: yarn electron-builder install-app-deps
      - run: yarn build-main
      - run: yarn build-renderer
      - run: yarn dist --config=.artifactName='${{ steps.filename.outputs.name }}'

      # Upload built executables
      - name: Upload executable
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.os }}
          path: ${{ github.workspace }}/release/*.${{ matrix.ext }}

      # Upload sourcemaps (only once)
      - name: Upload sourcemaps
        if: ${{ matrix.os == 'ubuntu-latest' }}
        uses: actions/upload-artifact@v2
        with:
          name: sourcemaps
          path: |
            ${{ github.workspace }}/dist/**/*.map
            ${{ github.workspace }}/dist/**/*.js

  publish:
    needs: [build, init_release]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/download-artifact@v2
        with:
          path: release
      - name: Locate release files
        id: locate
        run: |
          echo ::set-output name=macos::$(ls ${{ github.workspace }}/release/macos-latest/*)
          echo ::set-output name=ubuntu::$(ls ${{ github.workspace }}/release/ubuntu-latest/*)
          echo ::set-output name=windows::$(ls ${{ github.workspace }}/release/windows-latest/*)
          echo ::set-output name=sourcemaps::${{ github.workspace }}/release/sourcemaps
      - name: Release latest master
        uses: marvinpinto/action-automatic-releases@latest
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: master-build
          prerelease: true
          title: Development Build
          files: |
           ${{ steps.locate.outputs.macos }}
           ${{ steps.locate.outputs.ubuntu }}
           ${{ steps.locate.outputs.windows }}
      - name: Release new version
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
           ${{ steps.locate.outputs.macos }}
           ${{ steps.locate.outputs.ubuntu }}
           ${{ steps.locate.outputs.windows }}
      - name: Finalize Sentry release
        env:
          SENTRY_ORG: evan-purkhiser
          SENTRY_PROJECT: prolink-tools
          SENTRY_AUTH_TOKEN: "${{ secrets.SENTRY_AUTH_TOKEN }}"
        run: |
          RELEASE="$(git describe)"
          curl -sL https://sentry.io/get-cli/ | bash
          sentry-cli releases files "$RELEASE" upload-sourcemaps ${{ steps.locate.outputs.sourcemaps }}
          sentry-cli releases finalize "$RELEASE"
