
name: deploy server
on: [push]

jobs:
  deploy:
    name: deploy server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Build Dockerfile.server
        run: |
          docker build . -t evanpurkhiser/prolink-tools-server -f conf/Dockerfile.server

      - name: Publish
        run: |
          docker login --username=evanpurkhiser --password-stdin <<< "${{ secrets.DOCKER_HUB_TOKEN }}"
          docker push evanpurkhiser/prolink-tools-server:latest

      - name: Setup ssh-agent
        uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.DIGITAL_OCEAN_PRIVATE_KEY }}

      - name: Add known hosts for app.prolink.tools
        run: ssh-keyscan -H app.prolink.tools > ~/.ssh/known_hosts

      - name: Copy server-compose file
        run: |
          scp ./conf/server-compose.yml root@app.prolink.tools:./

      - name: Update images
        run: |
          ssh root@app.prolink.tools << EOF
            docker-compose -f ./server-compose.yml pull
            docker-compose -f ./server-compose.yml rm --stop -v prolink-tools
            docker-compose -f ./server-compose.yml up --detach
          EOF
